;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/CriticalPath/Content/Localization/CriticalPath
DestinationPath=Mods/GameFeatures/CriticalPath/Content/Localization/CriticalPath
ManifestName=CriticalPath.manifest
ArchiveName=CriticalPath.archive
ResourceName=CriticalPath.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de
CulturesToGenerate=es
CulturesToGenerate=fr
CulturesToGenerate=it
CulturesToGenerate=ja
CulturesToGenerate=ko
CulturesToGenerate=pl
CulturesToGenerate=pt-BR
CulturesToGenerate=ru
CulturesToGenerate=tr
CulturesToGenerate=zh-Hans
CulturesToGenerate=zh-Hant
CulturesToGenerate=bg
CulturesToGenerate=hu
CulturesToGenerate=no
CulturesToGenerate=uk
CulturesToGenerate=vi
CulturesToGenerate=ar
CulturesToGenerate=fa
CulturesToGenerate=th

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

